### ISSUE TITLE
Submit button in choosing.

### ISSUE THREAD

**Issue by AliEsam113** [alimelgohary/alimelgohary.github.io#34]
Sumbit button in choosing 
Otp fill number by number 
Colors 
Phone number is optional

**Comment by AliEsam113** [comment]
Remove submit button and make it checkbox

**Comment by fouadmo1223** [comment]
> Remove submit button and make it checkbox

done

**Comment by fouadmo1223** [comment]
> Remove submit button and make it checkbox

why do we need checkbox ?
